services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
    #Twig filter - 'localizeddate'
    Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    #Twig\Extensions\TextExtension: ~
