#index:
#    path: /
#    controller: App\Controller\DefaultController::index
snowtrick_homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
# Locales Binding
        _locale: '%app_locales%'
    defaults:
        template: blog/index.html.twig
        _locale: '%locale%'
